version: '3'
services:
  jekyll:
    image: jekyll/jekyll:3.8.6
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --livereload --incremental
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - site:/srv/jekyll/_site
      - bundle:/usr/local/bundle:cached
volumes:
  bundle:
  site:
